### ISSUE TITLE
there is not style for the message

### ISSUE THREAD

**Issue by carsonlius** [plasticbrain/PhpFlashMessages#13]
![1 y72fi3v8p65 uthgnm3h](https://user-images.githubusercontent.com/29518211/44516729-6b791e00-a6f8-11e8-85ee-414f058b1651.png)

what can i do?

**Comment by carsonlius** [comment]
someone has this same issue?

**Comment by marinesouth** [comment]
I am also having this issue presently how did you overcome it?
